name: Config option tests - ghcr.io/verapdf/rest:dev

on:
  schedule:
    - cron: "05 04 * * *"
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
      
      - name: Build and run Docker Image
        run: |
          docker build -t verapdf-rest:latest . && docker run -d -p 8080:8080 -p 8081:8081 verapdf-rest:latest
      
      
      - name: Check Docker Container
        id: check  
        run: |
          docker images
          docker ps


      - name: Preparing Linux packages(Bats-core and more ...)
        if: runner.os == 'Linux'
        working-directory: ./tests
        run: |
          echo whoami: $(whoami)
          mkdir ./results

          sudo apt-get update -y
          sudo apt install git -y

          git --version

          echo "Adding: bats-core.git, bats-support.git and bats-assert.git"
          git clone https://github.com/bats-core/bats-core.git ./bats
          git clone https://github.com/bats-core/bats-support.git ./bats-support
          git clone https://github.com/bats-core/bats-assert.git ./bats-assert

          ./bats/bin/bats -v

      - name: Config option ... running tests
        working-directory: ./tests
        run: |
          echo pwd: $PWD
          echo dir: $(ls ./)
          ./bats/bin/bats -r ./Options --output ./results

      - name: Generating report
        uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Results
          path: "./tests/results"
