name: Config option tests - ghcr.io/verapdf/rest:dev

on:
  schedule:
    - cron: "05 04 * * *"
  push:

jobs:
  test:
    name: Config option tests running in Docker container
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      verarest:
        image: ghcr.io/verapdf/rest:dev
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3


      - name: Check Docker Container 
        run: docker ps

      - name: Preparing Linux packages(Docker, Bats-core and more ...)
        if: runner.os == 'Linux'
        run: |
          echo pwd: $PWD
          mkdir ./results
          echo dir: $(ls ./)

          apt-get update -y
          apt install git -y

          git --version

          cd ./tests

          echo "Adding: bats-core.git, bats-support.git and bats-assert.git"
          git clone https://github.com/bats-core/bats-core.git ./bats
          git clone https://github.com/bats-core/bats-support.git ./bats-support
          git clone https://github.com/bats-core/bats-assert.git ./bats-assert

          ./bats/bin/bats -v

      - name: Config option ... running tests
        run: |
          echo pwd: $PWD
          echo dir: $(ls ./)
          ./bats/bin/bats -r ./Options --output ./results

      - name: Generating report
        uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Results
          path: "./results"
