name: Rest-api test call with ghcr.io/verapdf/rest:dev

on:
  schedule:
    - cron: "05 04 * * *"
  push:
    branches: ["Create-rest-api-tests"]

jobs:
  test:
    name: Rest-api test running
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      verarest:
        image: ghcr.io/verapdf/rest:dev
        ports:
          - 8080:8080
    steps:
      - uses: actions/checkout@v3

      - name: Preparing Linux packages(Python and more ...)
        if: runner.os == 'Linux'
        run: |
          echo pwd: $PWD
          echo dir: $(ls ./)

          apt-get update -y
          apt-get install python3 -y
          apt-get install python3-pip -y 

          pip install -r requirements.txt
          echo $(pip list)

          echo pwd: $PWD

      - name: Running rest-api tests ...
        run: |
          mkdir results    
          echo dir: $(ls ./)
          pytest -s -v  --html=./results/report.html  ./tests/

      - name: Generating report
        uses: actions/upload-artifact@v1
        if: success() || failure()
        with:
          name: Results
          path: "./results"
